version: "3.8"

services:
  python-api:
    container_name: python-api
    volumes:
      - ./python-api/app:/app
    build:
      context: ./python-api
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - PYTHONUNBUFFERED=1
    command: ["fastapi", "run", "app/main.py", "--port", "80"]
    networks:
      - net

networks:
  net:
    driver: bridge
